/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mp3tageditor.gui;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableColumn;
import mp3tageditor.model.Mp3Element;
import mp3tageditor.model.Mp3TagHandler;

/**
 *
 * @author utilizador
 */
public class Main extends javax.swing.JFrame {

  final JFileChooser fc = new JFileChooser();  
  private List<Mp3Element> mp3List = new ArrayList<Mp3Element>();
  /**
   * Creates new form Main
   */
  public Main() {
    fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    fc.setAcceptAllFileFilterUsed(false);
    initComponents();
    this.formatFilesTable();
    
  }
  
  private void formatFilesTable() {
    TableColumn column = null;
    for (int i = 0; i < 5; i++) {
      column = this.jTableFiles.getColumnModel().getColumn(i);
      if (i == 2) {
        column.setPreferredWidth(20); //third column is bigger
      } else {
        column.setPreferredWidth(200);
      }
    }
  }
  /*
  private void initFilesTable() {
    FileListTableModel model = new FileListTableModel();
    Object[][] data = new Object[this.mp3List.size()][model.getColumnCount()];
    int i = 0;
    for (Mp3Element mp3 : this.mp3List) {
       //"File Name", "New File Name", "Track #", "Title", "Artist", "Album"
      data[i][0] = mp3.getFileName();
      data[i][1] = mp3.getNewFileName();
      data[i][2] = mp3.getTrackNumber();
      data[i][3] = mp3.getTitle();
      data[i][4] = mp3.getArtist();
      data[i][5] = mp3.getAlbum();
      i++;
    }
    model.setData(data);
    this.jTableFiles = new JTable(model);    
    
  }
  */
  private FileListTableModel fillFilesTable() {    
    Object[][] data = new Object[this.mp3List.size()][6];
    int i = 0;
    for (Mp3Element mp3 : this.mp3List) {
      data[i][0] = mp3.getFileName();
      data[i][1] = mp3.getNewFileName();
      data[i][2] = mp3.getTrackNumber();
      data[i][3] = mp3.getTitle();
      data[i][4] = mp3.getArtist();
      data[i][5] = mp3.getAlbum();      
      /*
      this.jTableFiles.getModel().setValueAt(mp3.getFileName(), i, 0);
      this.jTableFiles.getModel().setValueAt(mp3.getNewFileName(), i, 1);
      this.jTableFiles.getModel().setValueAt(mp3.getTrackNumber(), i, 2);
      this.jTableFiles.getModel().setValueAt(mp3.getTitle(), i, 3);
      this.jTableFiles.getModel().setValueAt(mp3.getArtist(), i, 4);
      this.jTableFiles.getModel().setValueAt(mp3.getAlbum(), i, 5);      
      */
      i++;
    }
    FileListTableModel model = new FileListTableModel(data);
    return model;
  }
    
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    tfWorkingFolder = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    tfAlbumForList = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    tfArtistiForList = new javax.swing.JTextField();
    jButton2 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTableFiles = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    jLabel1.setText("Working folder:");

    tfWorkingFolder.setEditable(false);

    jButton1.setText("Change folder ...");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(tfWorkingFolder))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jButton1)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(tfWorkingFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jLabel2.setText("Folder Content:");

    jLabel8.setText("Set Album for List:");

    jLabel9.setText("Set Artist for List:");

    jButton2.setText("Set");

    jTableFiles.setModel(fillFilesTable());
    jScrollPane2.setViewportView(jTableFiles);

    jScrollPane1.setViewportView(jScrollPane2);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane1)
          .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel9)
              .addComponent(jLabel8))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(tfAlbumForList, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
              .addComponent(tfArtistiForList, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel8)
          .addComponent(tfAlbumForList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel9)
          .addComponent(tfArtistiForList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(jLabel2))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton2)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    int returnVal = fc.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) { 
      this.mp3List.clear();
      String workingPath = fc.getSelectedFile().toString();
      tfWorkingFolder.setText(workingPath);
      //JOptionPane.showMessageDialog(this, ex, "Error", JOptionPane.ERROR_MESSAGE);      
      try (Stream<Path> walk = Files.walk(Paths.get(workingPath))) {
        List<String> files = walk.map(x -> x.toString())
                .filter(f -> f.endsWith(".mp3")).collect(Collectors.toList());
        //result.forEach(System.out::println);
        for (String file : files) {
          File f = new File(file);
          Mp3Element el = new Mp3Element();
          Mp3TagHandler handler = new Mp3TagHandler(f);          
          el.setMp3File(f);
          el.setFileName(f.getName());
          String newFileName = String.format("%02d", handler.getTrackNumber().intValue()) + "." + f.getName();
          el.setNewFileName(newFileName);
          el.setTrackNumber(handler.getTrackNumber());
          el.setAlbum(handler.getAlbum());
          el.setArtist(handler.getArtist());
          el.setTitle(handler.getSongTitle());          
          this.mp3List.add(el);
        }
        this.jTableFiles.setModel(fillFilesTable());
      } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);      
        e.printStackTrace();
      }
    }
  }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Main().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable jTableFiles;
  private javax.swing.JTextField tfAlbumForList;
  private javax.swing.JTextField tfArtistiForList;
  private javax.swing.JTextField tfWorkingFolder;
  // End of variables declaration//GEN-END:variables
}

class FileListTableModel extends AbstractTableModel {
  private String[] columnNames = { "File Name", "New File Name", "Track #", "Title", "Artist", "Album" };
  private Object[][] data;
    
  public FileListTableModel(Object[][] list) {
    this.data = list;
  }
  
  public void setData(Object[][] list) {
    this.data = list;
  }
  
  public int getColumnCount() {
    return columnNames.length;
  }

  public int getRowCount() {
    return data.length;
  }

  public String getColumnName(int col) {
    return columnNames[col];
  }

  public Object getValueAt(int row, int col) {
    return data[row][col];
  }

  public Class getColumnClass(int c) {
    return getValueAt(0, c).getClass();
  }

  public boolean isCellEditable(int row, int col) {
  //Note that the data/cell address is constant,
  //no matter where the cell appears onscreen.
    if (col < 1) {
        return false;
    } else {
        return true;
    }
  }

  public void setValueAt(Object value, int row, int col) {
    data[row][col] = value;
    fireTableCellUpdated(row, col);
  }
}
